sudo: required

services:
  - docker

stages:
  - versioning

jobs:
  include:
    - stage: versioning
      language: node_js
      node_js: "10"
      install:
        - npm install -g semantic-release @semantic-release/release-notes-generator @semantic-release/commit-analyzer @semantic-release/changelog @semantic-release/github @semantic-release/git
      if: branch = master
      script:
        - semantic-release